name: riverpod_generator_example
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  auto_route: ^9.2.2
  package_info_plus: ^8.0.3
  dio: ^5.7.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1
  easy_refresh: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.png


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
